[package]
name = "cjk-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "io-util", "time"] }
tokio-rustls = "0"
anyhow = "1"
rustls = "0"
webpki-roots = "0"
httparse = "1"
urlencoding = "2"
log = "0"
env_logger = "0"
bytes = "1"
chacha20 = "0"
pin-project-lite = "0"
rand = "0"
base64 = "0"
clap = { version = "3", features = ["derive"] }