[package]
name = "cjk-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0"
async-std = { version = "1", features = ["attributes", "unstable"] }
anyhow = "1"
bytes = "1"
async-native-tls = "0"
futures = "0"