[package]
name = "cjk-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "io-util", "time", "sync"] }
async-std = { version = "1", features = ["attributes", "pin-project-lite", "futures-lite"] }
futures-lite = "1"
anyhow = "1"
httparse = "1"
log = "0"
env_logger = "0"
bytes = "1"
chacha20 = "0"
cipher = "0"
pin-project-lite = "0"
rand = "0"
base64 = "0"
serde = "1"
serde_derive = "1"
serde_json = "1"
aes = { version = "0", features = ["ctr"] }
url = "2"
clap = { version = "3", features = ["derive"] }
jni = "0"
regex = "1"
lazy_static = "1"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0"

[dev-dependencies]
futures-util = "0"

[target.'cfg(any(target_arch = "x86_64", target_arch = "x86", target_arch = "aarch64"))'.dependencies]
cpufeatures = "0"