[package]
name = "cjk-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1", features = ["attributes", "unstable"] }
anyhow = "1"
async-native-tls = "0"
futures = "0"
httparse = "1"
urlencoding = "2"
log = "0"
env_logger = "0"
bytes = "1"
clap = { version = "3", features = ["derive"] }