name: Rust

on:
  push:
    branches: [ master ]
    tags:
      - "v*"
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/master')
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.7
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: target
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
    - name: Run tests
      run: cargo test
  build_linux:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.7
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: target
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
    - name: Build Linux AMD64
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target=x86_64-unknown-linux-gnu
    - name: Build Linux AMD64
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target=aarch64-unknown-linux-gnu
        use-cross: true
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux_artifact
        path: target/**/release/proxy
  build_apple:
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.7
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: target
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
      - name: Build AMD64
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=x86_64-apple-darwin
      - name: Build Linux AMD64
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=apple
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: apple_artifacts
          path: target/**/release/proxy
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build_linux]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: homework
    - name: Create github release
      uses: softprops/action-gh-release@v1
      with:
        files: target/**/release/proxy