name: Rust

on:
  push:
    branches: [ master ]
    tags:
      - "v*"
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        include:
          - target: aarch64-unknown-linux-gnu
            cross: true
          - target: x86_64-apple-darwin
            cross: true
          - target: aarch64-apple-darwin
            cross: true
          - target: x86_64-unknown-linux-gnu
            cross: false
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.7
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: target
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.target }}
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
    - name: Run tests
      if: startsWith(github.ref, 'refs/heads/master')
      run: cargo test --release
    - name: Build package
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target=${{ matrix.target }}
        use-cross: ${{ matrix.cross }}
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./target/*/release/proxy